//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestWorldApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int TimeSheetId { get; set; }
        public string UserInfo { get; set; }
        public string Phone { get; set; }
        public bool Payed { get; set; }
        public string UserName { get; set; }
    
        public virtual TimeSheet TimeSheet { get; set; }
        public virtual User User { get; set; }
    }
}
